### ISSUE TITLE
Remove Terraform library from CLI

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#1189]
**Description**

The support for Terraform has to be removed from the CLI (usage and maintenance effort are not acceptable for the longerterm anymore).

The support for non-Gardener hyperscaler will be dropped and no longer supported. Support for Gardener stays by usage their native library calls.

- [x] Extract Gardener code from Terraform library and use it in CLI directly
- [x] Remove Terraform dependency
- [x] Archive repositories + remove these repositories from the update security scanner
- [x] Update documentation
- [x] Add release notes stating and motivating the removal of the hyperscaler provision commands

AC:
* `provision` command supports only K3d and Gardener - all other hyperscaler are removed
* terraform dependencies were dropped

**Reasons**

Remove low / unused code and reduce maintenance efforts on Kyma CLI side.

**Attachments**
