### ISSUE TITLE
Provide a support for sub-commands related to modules

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/cli#1432]
**Description**

Every Kyma module will require some configuration and setup, we want the users to have a single tool that they will be able to use during their development. Since configuration/setup flows and parameters will differ from module to module, there is no single way of handling those. We would need more of a modular approach when it comes to interacting with modules.

One of the solutions would be to introduce a sub-command framework that the module developers would be able to leverage in order to provide their own sub-commands for the CLI. Just like Busola's widgets, we could then present those as a single tool containing multiple packages related to specific modules (and have a semi-modular CLI as a side effect).

**Acceptance Criteria**
- [ ] CLI supports "pluggable" sub-commands related to modules
- [ ] Module developers are able to create their own sets of sub-commands per module they are delivering
- [ ] Technical guide for creating sub-commands is available

**Reasons**

We want the users to be able to configure specific modules via a single tool (the CLI).

**Comment by jakobmoellersap** [comment]
From my experience sub-commands included with different binaries can only be achieved with significant overhead: examples include gcloud CLI or even kubebuilder CLI with an external Plugin mechanism. Not only do we need a completely new bundling strategy for these commands, we also need to be able to pass information between commands seamlessly. kubebuilder handles this with a JSON interface and also that would require effort.

I think this entire epic is most likely heavily depending on how individual subcommands should work. Theoretically only core kyma modules would really need dedicated subcommands, I could think of only 2 use cases for every module:
- enable/disable module (which can be generic based on ModuleTemplate)
- install/remove module (also possible through the ModuleTemplate)
- inspect metrics (can happen generically by building on controller-runtime metrics)

Any other use case should IMO only be implemented in Busola via UI and made discoverable instead of hard coding into CLI commands. Let me know what you think :)

**Comment by janmedrek** [comment]
@jakobmoellersap yeah, I am more and more leaning towards having only a generic set of commands for the modules (enable/disable + list) and not doing the super-specific module actions via the CLI.

Anyways, I would start with gathering the requirements among the dev teams, perhaps there is something we've omitted. If not, we can just close this epic and focus on the generic part.

**Comment by janmedrek** [comment]
We won't be providing extended support for per-module commands. It's not that easy to implement a framework to support this and at this time we do not see enough value to invest that much effort into that.
