### ISSUE TITLE
Implement a MVP for `kyma app push` command

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/cli#2236]
**Description**

Implement a new `kyma app push` command that deploys k8s resources that are necessary to transform docker image definition (dockerfile)  into an application.
 
For example  (just a proposal at this stage)
```bash
//will use Dockerfile from the bar folder and use custom port 8080
kyma app push --name foo --dockerfile bar/Dockerfile --container-port 8080

//will not build the image but simply use nginx as app's image
kyma app push --name mynginx  --image nginx:latest
```

**AC**
The command should:
- should be available in command palette as soon as the connection to cluster is established (kubeconfig context is set)
- locate the `dockerfile` (lookup in the current folder by default),
- fail if no dockerfile was found and no `--image` flag was used,
- build the image  if needed 
- push the image to the registry (the command should read the in-cluster's docker registry `config.json`) if needed
- fail if `--dockerfile` option is used but no docker registry module is available in the cluster
- apply deployment (making use of exposed port information read from dockerfile)
- apply k8s service (making use of the port information read from dockerfile)
- (if api-gateway module is enabled) apply api-rule to expose all paths for the default, or user provided port and using the app name as a hostname

The definition of the command should be part of docker-registry module. 
Presence of api-gateway module should extend the command's default capability by adding the api-rule on top.

**Execution**
 - [x] https://github.com/kyma-project/cli/issues/2238
 - [x] https://github.com/kyma-project/cli/issues/2239
 - [x] https://github.com/kyma-project/cli/issues/2240
 - [x] https://github.com/kyma-project/cli/issues/2241

**Reasons**
Kyma users need a simple way to deploy containerised application without having any kubernetes knowledge.

**Comment by kwiatekus** [comment]
Stages:

 - create deployment based on `--name` and `--image` and `--containerPort` (3)
```
kyma alpha app push --name mynginx --image nginx:latest --containerPort xx
```

 - parse dockerfile to read port information and define k8s svc (2)

 - detection and support for api-gateway (3)
```
kyma alpha app push --name mynginx --image nginx:latest --containerPort xx --expose true
``` 

 - support custom image building (using lib, not docker daemon from host machine) (3)
```
kyma alpha app push --name myservice  --containerPort xx --expose true --dockerfile .
```
