### ISSUE TITLE
Support for updated Module Catalog

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/cli#2251]
**Description**

The recent changes required by the [Community Modules story](https://github.com/kyma-project/kyma/issues/18450) enable us to start working on the module related commands in kyma CLI. Multiple changes were introduced to the API of Kyma Lifecycle Manager, and thus, the new [planned](https://github.com/kyma-project/cli/issues/2221#issuecomment-2404978066) commands for module management should go along with them.

```
kyma module list <--installed/--available/--managed>
kyma module describe <MODULE_NAME> <--crds/--description/...>
kyma module deploy <MODULE_NAME> #<--namespace>
kyma module undeploy <MODULE_NAME> #<--namespace>
kyma module enable <MODULE_NAME> <--unmanaged> #<--namespace>
kyma module disable <MODULE_NAME> #<--namespace>
kyma module configure <MODULE_NAME> <FLAGS_FROM_CONFIGMAP> #<--namespace>
kyma module inspect <MODULE_NAME> <FLAGS_FROM_CONFIGMAP> <--output=text/json/yaml> #<--namespace>
```

**Reasons**

We want to have a set of convenient kyma CLI commands to interact with Kyma Module Catalog.

**Changes in Licecycle management API**

- ModuleTemplate CRD:
  - `.spec.channel` field was deprecated
  - `.spec.info` introduced, it includes basic information on the Module that can be displayed in Busola, such as repo/docu links, icons
  - `.spec.resources` introduced, it contains a reference to all the resources that need to be installed in order for the Module to be operational (used for manual installation)
  - `spec.associatedResources` introduced, it contains a list of all module-related CRDs
  - `.spec.manager` introduced, contains a reference to the Module manager, which can be used to determine whether manually installed module is operational or not
- ModuleReleaseMeta CRD introduced
  - It contains ties between module versions and channels used  

**Acceptance criteria**
User of managed cluster should be able to discover modules w/o enabling them, for example:
 - [x] discover available modules from catalog 
 ~- [ ] read details about the module (what API does it offer)~
 
User of managed cluster should be able to manage modules on his managed cluster, for example:
 - [x] enable managed module (with default module CR)
 - [x] enable managed module (with custom module CR)
 - [x] disable managed module
 - [x] unmanage module (keep module resources and API, but do not keep them managed by LFM )
 
 **Attachments**
 We have been provided with sample `moduletemplates` and `ModuleReleaseMeta` objects on development environment 
 https://github.com/kyma-project/lifecycle-manager/issues/2007#issuecomment-2476565696

**Comment by kwiatekus** [comment]
> Having the new Kyma CLI ready, we have to remember to update tutorials, including these in the Discovery Center missions. Please add it to the Definitions of Done for the epic.

Done [here](https://github.com/kyma-project/cli/issues/2232#issue-2626225236). thx
