### ISSUE TITLE
Increase Code Coverage

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/cli#492]
**Description**

As Kyma CLI is documented now as the only way to install Kyma, we should increase the overall quality and robustness. One step for this would be increasing code coverage by adding new unit tests. The current status is as follows:

<img width="782" alt="Screenshot 2020-07-08 at 12 29 48" src="https://user-images.githubusercontent.com/5543238/86909489-72588080-c118-11ea-9766-021623505803.png">

As a concrete aim for the task, we can say: 

- All the packages will have unit tests with a minimum of 30% coverage. 

>**NOTE:** This number should not make you ignore the packages with already more than 30% coverage as they might have important parts that are not covered. 

**Hint:**

You can use the following commands to see the current coverage on a browser:

```bash
go test ./... -coverprofile cp.out
go tool cover -html=cp.out
```

**Tasks**
Prerequisite:

- [x] Create mocks for all interfaces used in install package (use mockery).

Parallel tasks (1 file per developer):
- [x] cluster.go (Borja)
- [x] http.go (Borja)
- [x] installation.go (Suleyman)
- [x] service.go (Borja)
- [x] upgrade.go (Borja)
- [x] utils.go (Suleyman)
- [ ] docker.go (rakesh)

**Comment by suleymanakbas91** [comment]
As a result of the new tests:
- Overall test coverage increased from `31.5%` to `52.2%`.
- Installation package coverage increased from `10.1%` to `67.9%`.
